"""Central tunables for Rooster v2."""

from __future__ import annotations

import os


def _int_env(name: str, default: int) -> int:
    try:
        return int(os.environ.get(name, str(default)))
    except (TypeError, ValueError):
        return default


def _float_env(name: str, default: float) -> float:
    try:
        return float(os.environ.get(name, str(default)))
    except (TypeError, ValueError):
        return default


PLANNER_MODEL_DEFAULT = os.getenv("ROOSTER_PLANNER_MODEL", "gpt-5.5")
REVIEWER_MODEL_DEFAULT = os.getenv("ROOSTER_REVIEWER_MODEL", "gpt-5-mini")
SYNTHESIZER_MODEL_DEFAULT = os.getenv("ROOSTER_SYNTHESIZER_MODEL", "gpt-5.5")
MEMO_MODEL_DEFAULT = os.getenv("OPENAI_MODEL", "gpt-5.5")
MEMORY_MODEL_DEFAULT = os.getenv("ROOSTER_MEMORY_MODEL", "gpt-5-mini")

REASONING_PLANNER = os.getenv("ROOSTER_REASONING_PLANNER", "medium")
REASONING_REVIEWER = os.getenv("ROOSTER_REASONING_REVIEWER", "minimal")
REASONING_SYNTHESIZER = os.getenv("ROOSTER_REASONING_SYNTHESIZER", "low")
REASONING_MEMO = os.getenv("ROOSTER_REASONING_MEMO", "low")
REASONING_MEMORY = os.getenv("ROOSTER_REASONING_MEMORY", "minimal")

MAX_AGENT_STEPS_DEFAULT = _int_env("ROOSTER_MAX_AGENT_STEPS", 3)
MAX_AGENT_STEPS_RECOMMENDATION = _int_env("ROOSTER_MAX_AGENT_STEPS_RECOMMENDATION", 5)
MAX_PRIMITIVES = _int_env("ROOSTER_MAX_PRIMITIVES", 6)

MIN_VENTA_COUNT_DEFAULT = _int_env("ROOSTER_MIN_VENTA_COUNT", 3)
MIN_ALQUILER_COUNT_DEFAULT = _int_env("ROOSTER_MIN_ALQUILER_COUNT", 3)
DATA_CONFIDENCE_STRONG_MIN = _int_env("ROOSTER_DATA_CONFIDENCE_STRONG_MIN", 10)
DATA_CONFIDENCE_ADEQUATE_MIN = _int_env("ROOSTER_DATA_CONFIDENCE_ADEQUATE_MIN", 5)

PLANNER_MAX_OUTPUT_TOKENS = _int_env("ROOSTER_PLANNER_MAX_OUTPUT_TOKENS", 1400)
REVIEWER_MAX_OUTPUT_TOKENS = _int_env("ROOSTER_REVIEWER_MAX_OUTPUT_TOKENS", 500)
SYNTHESIZER_MAX_OUTPUT_TOKENS = _int_env("ROOSTER_SYNTHESIZER_MAX_OUTPUT_TOKENS", 2200)
MEMO_MAX_OUTPUT_TOKENS = _int_env("ROOSTER_MEMO_MAX_OUTPUT_TOKENS", 900)
MEMORY_MAX_OUTPUT_TOKENS = _int_env("ROOSTER_MEMORY_MAX_OUTPUT_TOKENS", 1200)
MEMORY_ASSISTANT_SUMMARY_CHARS = _int_env("ROOSTER_MEMORY_ASSISTANT_SUMMARY_CHARS", 6000)

PLANNER_SCHEMA_SNAPSHOT_CHARS = _int_env("ROOSTER_PLANNER_SCHEMA_SNAPSHOT_CHARS", 12000)
PLANNER_CONVERSATION_CONTEXT_CHARS = _int_env("ROOSTER_PLANNER_CONVERSATION_CONTEXT_CHARS", 8000)
PLANNER_LAST_ASSISTANT_CONTEXT_CHARS = _int_env("ROOSTER_PLANNER_LAST_ASSISTANT_CONTEXT_CHARS", 6000)
REVIEWER_TIMEOUT_SEC = _float_env("ROOSTER_REVIEWER_TIMEOUT_SEC", 12.0)

SYNTH_RESULT_SAMPLE_ROWS = _int_env("ROOSTER_SYNTH_RESULT_SAMPLE_ROWS", 12)
SYNTH_TABLE_FALLBACK_ROWS = _int_env("ROOSTER_SYNTH_TABLE_FALLBACK_ROWS", 20)
REVIEWER_RESULT_SAMPLE_ROWS = _int_env("ROOSTER_REVIEWER_RESULT_SAMPLE_ROWS", 8)
REVIEWER_RESULT_SAMPLE_DISPLAY_ROWS = _int_env("ROOSTER_REVIEWER_RESULT_SAMPLE_DISPLAY_ROWS", 4)

CHART_MIN_SCATTER_POINTS = _int_env("ROOSTER_CHART_MIN_SCATTER_POINTS", 2)
CHART_MIN_HISTOGRAM_ROWS = _int_env("ROOSTER_CHART_MIN_HISTOGRAM_ROWS", 4)
CHART_MIN_LINE_ROWS = _int_env("ROOSTER_CHART_MIN_LINE_ROWS", 2)
